/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import tema7_practica5_ejercicio1.Controlador;

/**
 *
 * @author 1GDAW09
 */
public class VentanaModificaciones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBajas
     */
    public VentanaModificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        bAlta = new javax.swing.JButton();
        bModificacion = new javax.swing.JButton();
        bBaja = new javax.swing.JButton();
        bListadoNumero = new javax.swing.JButton();
        bListadoContrato = new javax.swing.JButton();
        bListadoDepartamento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAlta = new javax.swing.JMenuItem();
        miModificacion = new javax.swing.JMenuItem();
        miBaja = new javax.swing.JMenuItem();
        miListado = new javax.swing.JMenu();
        miNumEmp = new javax.swing.JMenuItem();
        miContrato = new javax.swing.JMenuItem();
        miDepartamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bAlta.setText("Alta");
        bAlta.setFocusable(false);
        bAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlta);

        bModificacion.setText("Modificación");
        bModificacion.setFocusable(false);
        bModificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificacionActionPerformed(evt);
            }
        });
        jToolBar1.add(bModificacion);

        bBaja.setText("Baja");
        bBaja.setFocusable(false);
        bBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaActionPerformed(evt);
            }
        });
        jToolBar1.add(bBaja);

        bListadoNumero.setText("ListaNumero");
        bListadoNumero.setFocusable(false);
        bListadoNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListadoNumero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bListadoNumero);

        bListadoContrato.setText("ListaContrato");
        bListadoContrato.setFocusable(false);
        bListadoContrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListadoContrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bListadoContrato);

        bListadoDepartamento.setText("ListaContrato");
        bListadoDepartamento.setFocusable(false);
        bListadoDepartamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListadoDepartamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bListadoDepartamento);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lBienvenido.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBienvenido.setText("MODIFICACIONES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(lBienvenido, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Indica que operación vas a realizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jMenu1.setText("Personas");

        miAlta.setText("Alta");
        miAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaActionPerformed(evt);
            }
        });
        jMenu1.add(miAlta);

        miModificacion.setText("Modificación");
        miModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificacionActionPerformed(evt);
            }
        });
        jMenu1.add(miModificacion);

        miBaja.setText("Baja");
        miBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaActionPerformed(evt);
            }
        });
        jMenu1.add(miBaja);

        miListado.setText("Listado");

        miNumEmp.setText("Por número de empleado");
        miListado.add(miNumEmp);

        miContrato.setText("Por contrato");
        miListado.add(miContrato);

        miDepartamento.setText("Por departamento");
        miListado.add(miDepartamento);

        jMenu1.add(miListado);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Controlador.salir();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        Controlador.salir();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void miAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaActionPerformed
        Controlador.irVentanaAltas(this);
    }//GEN-LAST:event_miAltaActionPerformed

    private void miModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificacionActionPerformed
        Controlador.irVentanaModificaciones(this);
    }//GEN-LAST:event_miModificacionActionPerformed

    private void miBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaActionPerformed
        Controlador.irVentanaBajas(this);
    }//GEN-LAST:event_miBajaActionPerformed

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        miAlta.doClick();
    }//GEN-LAST:event_bAltaActionPerformed

    private void bModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificacionActionPerformed
        miModificacion.doClick();
    }//GEN-LAST:event_bModificacionActionPerformed

    private void bBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaActionPerformed
        miBaja.doClick();
    }//GEN-LAST:event_bBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bListadoContrato;
    private javax.swing.JButton bListadoDepartamento;
    private javax.swing.JButton bListadoNumero;
    private javax.swing.JButton bModificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lBienvenido;
    private javax.swing.JMenuItem miAlta;
    private javax.swing.JMenuItem miBaja;
    private javax.swing.JMenuItem miContrato;
    private javax.swing.JMenuItem miDepartamento;
    private javax.swing.JMenu miListado;
    private javax.swing.JMenuItem miModificacion;
    private javax.swing.JMenuItem miNumEmp;
    // End of variables declaration//GEN-END:variables
}
