/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import tema8_practica1_ejercicio2.Controlador;

/**
 *
 * @author 1GDAW09
 */
public class VentanaBorrar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBorrar
     */
    public VentanaBorrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBorrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bAceptarBorrar = new javax.swing.JButton();
        bCancelarBorrar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        bAnnadir = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        miBorrar = new javax.swing.JMenu();
        miAnnadirEvento = new javax.swing.JMenuItem();
        miBorrarEvento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        miBienvenida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        panelBorrar.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Borrar un Evento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        panelBorrar.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelBorrar.add(jLabel10, gridBagConstraints);

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        panelBorrar.add(tfNombre, gridBagConstraints);

        bAceptarBorrar.setText("Aceptar");
        bAceptarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(bAceptarBorrar);

        bCancelarBorrar.setText("Cancelar");
        bCancelarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(bCancelarBorrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelBorrar.add(jPanel2, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bAnnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sumar.png"))); // NOI18N
        bAnnadir.setFocusable(false);
        bAnnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnnadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnadirActionPerformed(evt);
            }
        });
        jToolBar1.add(bAnnadir);

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        bBorrar.setFocusable(false);
        bBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        jToolBar1.add(bBorrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelBorrar.add(jToolBar1, gridBagConstraints);

        getContentPane().add(panelBorrar);

        miBorrar.setText("Eventos");

        miAnnadirEvento.setText("Añadir evento");
        miAnnadirEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnnadirEventoActionPerformed(evt);
            }
        });
        miBorrar.add(miAnnadirEvento);

        miBorrarEvento.setText("Cancelar evento");
        miBorrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarEventoActionPerformed(evt);
            }
        });
        miBorrar.add(miBorrarEvento);

        jMenuBar1.add(miBorrar);

        jMenu2.setText("Salir");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu2.add(miSalir);

        miBienvenida.setText("Volver a la página de bienvenida");
        miBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBienvenidaActionPerformed(evt);
            }
        });
        jMenu2.add(miBienvenida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarBorrarActionPerformed
        try
        {
            Controlador.borrarEvento(tfNombre.getText());
            tfNombre.setText("");
        }
        catch(Exception e)
        {
            System.out.println(e.getClass() + e.getMessage());
        }
    }//GEN-LAST:event_bAceptarBorrarActionPerformed

    private void bCancelarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarBorrarActionPerformed
        miBienvenida.doClick();
    }//GEN-LAST:event_bCancelarBorrarActionPerformed

    private void miAnnadirEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnnadirEventoActionPerformed
        Controlador.irVentanaAnnadir(this);
    }//GEN-LAST:event_miAnnadirEventoActionPerformed

    private void miBorrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarEventoActionPerformed
        tfNombre.setText("");
    }//GEN-LAST:event_miBorrarEventoActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        Controlador.salir();
    }//GEN-LAST:event_miSalirActionPerformed

    private void miBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBienvenidaActionPerformed
        Controlador.irVentanaBienvenida(this);
    }//GEN-LAST:event_miBienvenidaActionPerformed

    private void bAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnadirActionPerformed
        miAnnadirEvento.doClick();
    }//GEN-LAST:event_bAnnadirActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        miBorrarEvento.doClick();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        bAceptarBorrar.doClick();
    }//GEN-LAST:event_tfNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBorrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptarBorrar;
    private javax.swing.JButton bAnnadir;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelarBorrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miAnnadirEvento;
    private javax.swing.JMenuItem miBienvenida;
    private javax.swing.JMenu miBorrar;
    private javax.swing.JMenuItem miBorrarEvento;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JPanel panelBorrar;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
