/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import tema8_practica2.Controlador;

/**
 *
 * @author 1GDAW09
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAltaCliente = new javax.swing.JMenuItem();
        miBajaCliente = new javax.swing.JMenuItem();
        miModificarCliente = new javax.swing.JMenuItem();
        miConsultarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAltaAbogado = new javax.swing.JMenuItem();
        miBajaAbogado = new javax.swing.JMenuItem();
        miModificarAbogado = new javax.swing.JMenuItem();
        miConultaAbogado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAltaCaso = new javax.swing.JMenuItem();
        miBajaCaso = new javax.swing.JMenuItem();
        miModificarCaso = new javax.swing.JMenuItem();
        miConsultaCaso = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 400));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gabinete de abogados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 10, 100);
        getContentPane().add(jButton1, gridBagConstraints);

        jMenu1.setText("Clientes");

        miAltaCliente.setText("Dar un cliente de alta");
        miAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miAltaCliente);

        miBajaCliente.setText("Dar un cliente de baja");
        miBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miBajaCliente);

        miModificarCliente.setText("Modificar un cliente");
        miModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miModificarCliente);

        miConsultarCliente.setText("Consultar clientes");
        miConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Abogados");

        miAltaAbogado.setText("Dar un abogado de alta");
        miAltaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaAbogadoActionPerformed(evt);
            }
        });
        jMenu2.add(miAltaAbogado);

        miBajaAbogado.setText("Dar un abogado de baja");
        miBajaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaAbogadoActionPerformed(evt);
            }
        });
        jMenu2.add(miBajaAbogado);

        miModificarAbogado.setText("Modificar un abogado");
        miModificarAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarAbogadoActionPerformed(evt);
            }
        });
        jMenu2.add(miModificarAbogado);

        miConultaAbogado.setText("Consultar abogados");
        miConultaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConultaAbogadoActionPerformed(evt);
            }
        });
        jMenu2.add(miConultaAbogado);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Casos");

        miAltaCaso.setText("Dar un caso de alta");
        jMenu3.add(miAltaCaso);

        miBajaCaso.setText("Dar un caso de baja");
        jMenu3.add(miBajaCaso);

        miModificarCaso.setText("Modificar un caso");
        jMenu3.add(miModificarCaso);

        miConsultaCaso.setText("Consultar casos");
        jMenu3.add(miConsultaCaso);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Volver");

        miVolver.setText("Volver");
        jMenu4.add(miVolver);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controlador.salir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void miAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaClienteActionPerformed
        Controlador.irpantallaAltaClientes(this);
    }//GEN-LAST:event_miAltaClienteActionPerformed

    private void miBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaClienteActionPerformed
        Controlador.irpantallaBajaClientes(this);
    }//GEN-LAST:event_miBajaClienteActionPerformed

    private void miModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarClienteActionPerformed
        Controlador.irpantallaModificarClientes(this);
    }//GEN-LAST:event_miModificarClienteActionPerformed

    private void miConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarClienteActionPerformed
        Controlador.irpantallaConsultaClientes(this);
    }//GEN-LAST:event_miConsultarClienteActionPerformed

    private void miAltaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaAbogadoActionPerformed
        Controlador.irpantallaAltaAbogados(this);
    }//GEN-LAST:event_miAltaAbogadoActionPerformed

    private void miBajaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaAbogadoActionPerformed
        Controlador.irpantallaBajaAbogados(this);
    }//GEN-LAST:event_miBajaAbogadoActionPerformed

    private void miModificarAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarAbogadoActionPerformed
        Controlador.irpantallaModificarAbogados(this);
    }//GEN-LAST:event_miModificarAbogadoActionPerformed

    private void miConultaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConultaAbogadoActionPerformed
        Controlador.irpantallaConsultaAbogados(this);
    }//GEN-LAST:event_miConultaAbogadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAltaAbogado;
    private javax.swing.JMenuItem miAltaCaso;
    private javax.swing.JMenuItem miAltaCliente;
    private javax.swing.JMenuItem miBajaAbogado;
    private javax.swing.JMenuItem miBajaCaso;
    private javax.swing.JMenuItem miBajaCliente;
    private javax.swing.JMenuItem miConsultaCaso;
    private javax.swing.JMenuItem miConsultarCliente;
    private javax.swing.JMenuItem miConultaAbogado;
    private javax.swing.JMenuItem miModificarAbogado;
    private javax.swing.JMenuItem miModificarCaso;
    private javax.swing.JMenuItem miModificarCliente;
    private javax.swing.JMenuItem miVolver;
    // End of variables declaration//GEN-END:variables
}
